FROM ruby:2.6.4
RUN apt-get update -y && apt-get install -y nodejs npm default-libmysqlclient-dev
RUN npm install -g npm
RUN npm install -g yarn

WORKDIR /workspace
COPY ./Gemfile ./Gemfile
COPY ./Gemfile.lock ./Gemfile.lock
RUN bundle install

COPY ./package.json ./package.json
COPY ./yarn.lock ./yarn.lock
RUN yarn install

COPY . .
RUN mkdir tmp/pids
ENV RAILS_MASTER_KEY=''
ENV RAILS_ENV='production'
ENV RACK_ENV='production'

# Add a script to be executed every time the container starts.
COPY docker_app_entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/docker_app_entrypoint.sh
ENTRYPOINT ["docker_app_entrypoint.sh"]

CMD ["bundle", "exec", "puma", "-C", "config/puma.rb"]
